hashicorp/hcl-lang

- decoder/body_candidates.go
- decoder/body_decoder_test.go
- go.mod
- go.sum
- schema/attribute_schema.go
- schema/attribute_schema_test.go
- schema/body_schema.go
This is to differentiate between fields which are
computed-only (IsComputed: true, IsOptional: false)
and computed + optional (IsComputed: true, IsOptional: true).
Technically we could assume IsOptional: true when IsComputed: false,
but that would likely make a future serialization story more complex
and introduce potential confusion for callers where they may just read
raw struct field, instead of going through some functions
which set the defaults.
> schema/attribute: introduce explicit IsOptional field

- decoder/candidates.go
- decoder/candidates_test.go
Fixes wrong range calculation for newText/snippet when the position is near EOF, as reported in https://github.com/hashicorp/terraform-ls/issues/295
> Fix calculation of range for candidates near EOF

- decoder/block_candidates.go
- decoder/candidates_test.go
- lang/candidate.go
See https://github.com/hashicorp/vscode-terraform/issues/373
The inline comments hopefully explain the implementation and how it can be used.
I think this might survive even if/when the problem is solved on the LSP level https://github.com/microsoft/language-server-protocol/issues/565 because the server still needs to decide which blocks have labels that are in fact completable.
> lang/Candidate: Add TriggerSuggest field

- decoder/symbols.go
- decoder/symbols_test.go
This provides support for `workspace/symbol` method on the language server side:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_symbol
Currently we'd do a simple exact match on the symbol's "name" - e.g. `resource "aws_vpc" "main"`, but I reckon longer term we may want to add some loose matching too, or perhaps compare the query against the common `block.label1.label2` pattern.
Currently we only query the top-level symbols, but we may consider querying nested symbols, i.e. nested attributes and blocks too eventually. It just isn't clear to me yet what the UX implications of that would be in bigger modules with many blocks.
> Introduce method for querying symbols across files

- decoder/decoder.go
- decoder/hover.go
- decoder/links.go
- decoder/links_test.go
- lang/link.go
- schema/body_schema.go
This is in preparation for implementation of `textDocument/documentLink` on the language server side:
https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentLink
https://github.com/hashicorp/terraform-schema/pull/10 adds the actual links to the Registry for Terraform providers and depends on this PR
Initially I decided to only implement this for _dependent_ block bodies, which in case of Terraform applies to provider, resource and data source blocks as that's the part of configuration which has more easily linkable and versioned docs.
Relatedly I also limited the implementation initially for the 1st level, as we don't have dependent bodies at any deeper levels.
> Introduce LinksInFile method

- .github/.codecov.yml
This enables [codecov](https://about.codecov.io/) integration in the most minimal way possible. In particular it suppresses the PR comments and status, [such as these](https://github.com/hashicorp/hcl-lang/pull/9#issuecomment-779693393). Personally I don't find them as useful due to the fact that they can't be configured in more meaningful way - to avoid the noise on low-impact PRs, such as docs updates.
That said I do find codecov in itself useful when working on bigger PRs which refactor or introduce a lot of LOC - at which point I would just go straight to codecov.io and review the coverage impact of that particular PR there.
> ci: Enable codecov

- decoder/symbols.go
This was an oversight where the string slice was just being converted to [`StringSlice`](https://golang.org/pkg/sort/#StringSlice) (type) which in itself (obviously) doesn't sort the slice.
This fixes the following flaky test:
```
=== RUN   TestDecoder_Symbols_basic
symbols_test.go:236: unexpected symbols:   []decoder.Symbol{
- 	&decoder.BlockSymbol{
- 		Type:   "resource",
- 		Labels: []string{"aws_vpc", "main"},
- 		rng:    s"first.tf:2,1-4,2",
- 		nestedSymbols: []decoder.Symbol{
- 			&decoder.AttributeSymbol{AttrName: "cidr_block", Type: cty.Type{...}, rng: s"first.tf:3,3-29"},
- 		},
- 	},
+ 	&decoder.BlockSymbol{
+ 		Type:   "provider",
+ 		Labels: []string{"google"},
+ 		rng:    s"second.tf:2,1-5,2",
+ 		nestedSymbols: []decoder.Symbol{
+ 			&decoder.AttributeSymbol{AttrName: …
```
> fix: Make sure Symbols() output is sorted

- decoder/symbols.go
- decoder/symbols_test.go
- lang/symbol_kind.go
Because symbol navigation is (intentionally) _not_ schema driven we cannot tell whether the `ScopeTraversalExpr` represents a keyword or any more complex reference/traversal. However it's still helpful to differentiate such an expression from other (unrecognized) expressions.
> Add Traversal as symbol kind

- decoder/attribute_candidates.go
- decoder/body_decoder_test.go
- decoder/candidates_test.go
- decoder/expression_candidates.go
- decoder/expression_candidates_test.go
- decoder/expression_constraints.go
- decoder/hover.go
- decoder/hover_expressions_test.go
- decoder/hover_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_expr_test.go
- schema/expressions.go
This is to support recent changes in core schema introduced in Terraform 0.15 where an object can contain traversals - i.e. not literals.
> Add support for ObjectExpr expression type

- decoder/decoder.go
- decoder/decoder_test.go
This fixes a conversion function which was previously not covered by tests.
This bug in combination with another bug https://github.com/hashicorp/terraform-schema/pull/28 caused the dependent schemas of `resource` or `data` block to be looked up basically freely without the `provider` attribute being considered.
In other words most of the time it _looked like_ everything is working fine, but there were some configurations being misinterpreted, e.g.
```hcl
terraform {
required_providers {
rand = {
source  = "hashicorp/random"
version = "3.0.0"
}
}
}
resource "random_string" "name" {
provider = rand
}
```
It is true that providers of `hashicorp` (default) namespace do not require explicit `required_providers` entry, however if they do have one, it should be respected.
Here due to the …
> Fix attribute lookup for dependent schemas

- decoder/expression_candidates.go
- decoder/expression_candidates_test.go
- decoder/expression_constraints.go
- decoder/hover.go
- decoder/hover_expressions_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_expr_test.go
- decoder/symbols.go
- decoder/symbols_test.go
This addresses https://github.com/hashicorp/terraform-ls/issues/447
> fix: avoid crashes on unknown keys

- decoder/expression_candidates.go
- decoder/expression_candidates_test.go
- decoder/expression_constraints.go
- decoder/hover.go
- decoder/hover_expressions_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_expr_test.go
- schema/expressions.go
This aims to support "nested attribute type" introduced as part of Terraform 0.15, support for which was added to `terraform-json` in https://github.com/hashicorp/terraform-json/pull/28
None of these expression types are currently supported by the Terraform SDK, so providers can't really produce them yet (unless they somehow bypass the SDK and talk gRPC directly).
Additionally tuples are not supported in the SDK at all:
https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk@v1.16.1/helper/schema#ValueType
> Introduce ListExpr, SetExpr and TupleExpr

- decoder/copiers.go
- decoder/decoder.go
This follows an upstream bug fix in copystructure: https://github.com/mitchellh/copystructure/pull/35
Whilst working on a new feature of the Terraform LS which also uses `copystructure` I needed to register some other (different) custom copiers there and I observed misbehaviours caused by the fact that we register custom copiers here globally and then as a result of calling `mergeBlockBodySchemas` these custom _global_ copiers would get overwritten downstream.
This patch eliminates that problem by avoiding global state for copiers and instead declares them locally.
--- 
I already used a similar patch in LS, so the global state doesn't affect me there, but I'm patching it here anyway to prevent future weirdness from occurring.
> Avoid registering copystructure copiers globally

- decoder/candidates_test.go
- decoder/label_candidates.go
https://github.com/hashicorp/hcl-lang/pull/25 apparently uncovered another edge case in completion of labels.
Specifically with #25 applied we'd "correctly" base our suggestions for label on all available dependency keys, which are essentially duplicated, as is demonstrated in the attached test.
I am not sure yet what's the best way of approaching this (admittedly not common) situation, but I do think that user most likely wouldn't expect duplicated entries, especially when they have the exact same meaning.
> Avoid completing duplicate label candidates

- decoder/attribute_candidates.go
- decoder/candidates.go
- decoder/candidates_test.go
- decoder/decoder.go
- decoder/errors.go
- decoder/expression_candidates.go
- decoder/expression_candidates_test.go
- decoder/expression_constraints.go
- decoder/hover.go
- decoder/hover_expressions_test.go
- decoder/references.go
- decoder/references_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_expr_test.go
- decoder/symbols.go
- lang/address_steps.go
- lang/candidate.go
- lang/candidate_kind_string.go
- lang/references.go
- lang/semantic_token.go
- lang/semantic_token_type_string.go
- schema/address_step.go
- schema/attribute_schema.go
- schema/attribute_schema_test.go
- schema/block_schema.go
- schema/block_schema_test.go
- schema/block_type.go
- schema/body_schema.go
- schema/expressions.go
- schema/expressions_test.go
Closes #2
--- 
In general the schema recognizes two types of references - (1) type-aware, and (2) type-less
In Terraform type-aware references are commonly used to set values of fields via reference. For example:
```hcl
key_name = aws_key_pair.iac_in_action.key_name
```
Here `key_name` is of type `string` and relatedly `aws_key_pair.iac_in_action.key_name` points to a field of type `string`.
Type-less references are used to draw an explicit dependency between resources, e.g.
```hcl
resource "aws_instance" "example" {
// ...
depends_on = [ aws_s3_bucket.example ]
}
resource "aws_s3_bucket" "example" {
// ...
}
```
Here in this particular context of `depends_on`, `aws_s3_bucket.example` only represents a "pointer" to the lower block, but isn't concerned about what data (whether any) it …
> Add support for TraversalExpr

- decoder/attribute_candidates.go
- decoder/body_decoder_test.go
- decoder/candidates_test.go
- decoder/hover_test.go
- schema/attribute_schema.go
- schema/attribute_schema_test.go
So that sensitive attributes can be flagged.
> Add `IsSensitive` to `AttributeSchema`

- decoder/hover.go
- decoder/hover_test.go
- schema/body_schema.go
For provider linking we initially wanted (and still want) links both in hover and explicitly exposed via `LinksInFile` and corresponding [`textDocument/documentLink` LSP method](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentLink).
However there are cases where direct linking would be too distracting and inappropriate, given how it's implemented in VS Code and probably elsewhere. In other words we don't want so much code to be underlined all the time.
Providing a link in a more subtle way in hover data is still valuable, so this field aims to strike the balance.
> BodySchema: Introduce (dedicated) HoverURL

- decoder/hover.go
- decoder/hover_test.go
Previously we only added links to dependent labels on hover.
This also enables links for block types:
> Provide relevant HoverURL in hover over block types

- decoder/expression_candidates.go
- decoder/expression_candidates_test.go
- decoder/expression_constraints.go
- decoder/hover.go
- decoder/hover_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_test.go
- lang/semantic_token.go
- lang/semantic_token_type_string.go
- schema/expressions.go
So that completion, hover and semantic-tokens work for variable `type`.
Related to hashicorp/terraform-ls#490
> Add type declarations for variable `type`

- decoder/dependent_body.go
- decoder/dependent_body_test.go
As demonstrated in the test this PR fixes a bug where we'd have a "dependent" attribute present, but not matching any dependent body in the map, which would then cause the lookup to fail entirely.
For example this can represent a following situation:
```hcl
data "terraform_remote_state" "name" {
backend = 
}
```
where (dependent) `backend` attribute is present but yet to be completed. In such case we should fall back to the previously matched `DependentBody`.
> fix nested DependentBody lookup

- decoder/expression_candidates.go
- decoder/expression_candidates_test.go
- schema/expressions.go
- schema/expressions_test.go
This is to help communicate deprecated backends in https://github.com/hashicorp/terraform-schema/pull/52
> LiteralValue: Introduce IsDeprecated

- decoder/hover.go
- decoder/hover_test.go
To display whether an object attribute is optional; for instance, in the
object variable below, `opt_attr` is optional.
```
variable "test" {
type = object({
opt_attr = optional(string)
}
)
}
```
> Add `optional` in hover content for object attrs

- decoder/references.go
- decoder/references_test.go
- schema/attribute_schema.go
- schema/attribute_schema_test.go
- schema/block_schema.go
This enables the schema to represent Terraform's locals and variables, including untyped variable defaults.
Related to https://github.com/hashicorp/terraform-ls/issues/491
> schema: Make types of references more flexible

- decoder/candidates.go
- decoder/candidates_test.go
- schema/label_schema.go
This aims to address an edge case where dependent body schemas are in use, but using them for completion wouldn't be appropriate.
See https://github.com/hashicorp/terraform-ls/issues/552 for more concrete example with variables.
> schema/decoder: Make label completion more flexible

- decoder/expression_candidates.go
- decoder/expression_candidates_test.go
- decoder/references.go
- decoder/references_test.go
This makes completion "less verbose" by hiding any matching nested references and instead always present the nearest top-level match based on the prefix.
We can revisit the idea of making the old verbose completion opt-in behaviour, but I think this is better default for any more complex configurations which would easily cross 100 completion items with just references alone.
> Provide step based completion

- decoder/expression_candidates.go
- decoder/references.go
- decoder/references_test.go
Previously we would only decode references to elements within list/map blocks, e.g. `customblock[0].attribute` or `customblock["one"].attribute`. Terraform however also allows targeting all instances of a list/map block together as a list or a map (hence block type names).
We were also previously entirely ignoring set block types. While nested data within set blocks are not addressable, the set itself is.
Additionally the decoder also now respects `MaxItems` of a `BlockSchema` and will no longer create references to any list/set/map elements which are over the limit. e.g. `list_block[1]` reference won't be created if `list_block` has `MaxItems: 1`.
TL;DR this creates new references such as
- `list_block[0]` (`cty.Object`)
- `map_block["one"]` (`cty.Object`)
- `set_block` (`cty.Set`)
> fix: referencing of list, set and map blocks

- decoder/expression_candidates.go
- decoder/reference_origins.go
- decoder/reference_origins_test.go
- decoder/reference_targets.go
- decoder/reference_targets_test.go
- lang/reference_origin.go
This is to provide support for "go to definition" and "go to declaration", as described in hashicorp/vscode-terraform#671
> Introduce `ReferenceOriginAtPos` & `ReferenceTargetForOrigin`

- decoder/reference_targets.go
- decoder/reference_targets_test.go
- lang/address_steps.go
Parsing the following config would lead to the creation of circular references, which then cause a loop while copying the references in LS:
```hcl
locals {
top_obj = {
first = {
attr = "val"
}
second = {
attr = "val"
}
third = {
attr = "val"
}
fourth = {
attr = "val"
}
}
}
```
> fix: avoid circular references to complex attribute types

- decoder/decoder.go
- decoder/reference_origins.go
- decoder/reference_origins_test.go
- decoder/reference_targets.go
- lang/reference_origin.go
TODO
- matching targets of unknown type (e.g. where the value & type is determined from other external sources - e.g. from state in Terraform)
> Introduce `ReferenceOriginsForTarget` & `CollectReferenceOrigins`

- decoder/reference_origins.go
- decoder/reference_origins_test.go
Previously when looking up origins for targets with nested targets we'd produce duplicate results due to this bug which is being patched. This probably wouldn't have any effect on the end user in most language clients (assuming they just deduplicate), but it's a bug nonetheless.
> fix: avoid matching duplicate ref origins

- decoder/reference_origins.go
- decoder/reference_origins_test.go
- decoder/reference_targets.go
This was mostly an oversight in the initial implementation, discovered as part of https://github.com/hashicorp/terraform-ls/issues/585
The same problem still exists for reference targets, but dependent schema in Terraform's context AFAICT doesn't contain custom addresses at this point, so this is currently not a priority - but I left a TODO there.
> Reflect dependent schemas when collecting ref origins

- decoder/reference_origins.go
- decoder/reference_origins_test.go
- decoder/reference_targets.go
- decoder/reference_targets_test.go
This PR introduces two API changes:
- from `OutermostReferenceTargetAtPos(...) (*lang.ReferenceTarget, ...)`
to `OutermostReferenceTargetsAtPos(...) (lang.ReferenceTargets, ...)`
- from `InnermostReferenceTargetAtPos(...) (*lang.ReferenceTarget, ...)`
to `InnermostReferenceTargetsAtPos(...) (lang.ReferenceTargets, ...)`
This better reflects the fact that there can be more than a single target for the same position, for example in Terraform, a resource or module can have both type-less and typed references pointing to the same block.
> Reflect that there can be multiple targets at a position

- decoder/expression_candidates.go
- decoder/expression_constraints.go
- decoder/hover.go
- decoder/reference_origins.go
- decoder/reference_origins_test.go
- decoder/reference_targets.go
- decoder/reference_targets_test.go
- decoder/semantic_tokens.go
- lang/reference_origin.go
- schema/expressions.go
We collect origins and targets in parallel (not sequentially) and we cannot know which constraint would match the target if the origin has multiple constraints - such as in Terraform `resource` blocks have `depends_on` which may contain multiple `schema.TraversalExpr` with different `ScopeId`s.
Matching of the scope needs to be done only against decoded targets, not sooner.
> Reflect that ref origins have multiple constraints

- decoder/decoder.go
- decoder/reference_targets.go
- decoder/reference_targets_test.go
- schema/body_schema.go
- schema/targetable.go
- schema/targetable_test.go
This is to aid with expressing Terraform module output references.
For example a module block such as
```hcl
module "example" {
source = "./submodule"
}
```
can be targeted as `module.example.foo`, assuming there is `foo` output declared within `./submodule`:
```hcl
output "foo" {
value = "..."
}
```
It is not possible to express this as computed-only attributes because module inputs and outputs can have same names, so there would be potential for conflict.
> BodySchema: Introduce TargetableAs

- decoder/expression_candidates_test.go
- decoder/hover_expressions_test.go
- decoder/reference_origins.go
- decoder/reference_origins_test.go
- schema/expressions.go
This is to address a bug reported in https://github.com/hashicorp/terraform-ls/issues/592 where origins were being associated with incorrect expression constraints (e.g. map of traversals instead of traversal).
There is still more work to do in terms of fully supporting nested expressions, but this at least covers the most common and obvious cases of list, set, tuple, map and object expressions. Remaining expression types are to be dealt with as part of https://github.com/hashicorp/terraform-ls/issues/496 (tracked there but most of the work will be done in this repo).
> fix: associate correct constraints with nested origins

- decoder/semantic_tokens.go
- decoder/semantic_tokens_expr_test.go
This fixes a crash that can be demonstrated by the attached test.
It was initially reported as part of https://github.com/hashicorp/vscode-terraform/issues/707#issuecomment-891008775
> decoder: Skip unknown tuple element

- decoder/body_candidates.go
- decoder/body_candidates_test.go
This is to compliment https://github.com/hashicorp/terraform-schema/pull/69 by avoiding to complete a block if there's an attribute of the same name.
> decoder: prefer attribute over block in case of duplicate name

- decoder/label_candidates.go
- decoder/label_candidates_test.go
Previously we didn't correctly limit the number of candidates returned for a label completion, which in some extreme cases would mean that for Terraform resource we would send ~700 items just for AWS provider + any more hundreds for any other providers declared in the module.
> fix: Limit label completion items to maxCandidates (100)

- .github/workflows/ci.yml
This aligns the config more with the one we use for `terraform-ls`.
Namely the default GHA timeout is 6 hours and there are known cases of builds sometimes getting stuck (due to what seems a temporary issue on GitHub's side usually) which in turn consumes credits, i.e. cost money. Our builds here almost never cross the 2 min mark, but I set it conservatively to 5 minutes.
The [default token permissions](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) depend on Enterprise policy settings, but either way we don't need anything other than cloning the repo to run the tests, so this patch reflects that.
> ci: Reduce timeout & token permissions

- decoder/body_candidates.go
- decoder/label_candidates.go
- lang/candidate.go
This was caught by a flaky test on `main` after merging https://github.com/hashicorp/hcl-lang/pull/85
```
=== RUN   TestDecoder_CandidateAtPos_incompleteLabels
label_candidates_test.go:102: unexpected candidates:   lang.Candidates{
List: []lang.Candidate{
{
- 			Label:        "first",
+ 			Label:        "second",
Description:  {},
Detail:       "",
IsDeprecated: false,
TextEdit: lang.TextEdit{
Range:   {Filename: "test.tf", Start: {Line: 1, Column: 14, Byte: 13}, End: {Line: 1, Column: 14, Byte: 13}},
- 				NewText: "first",
+ 				NewText: "second",
- 				Snippet: "first",
+ 				Snippet: "second",
},
AdditionalTextEdits: nil,
Kind:                s"LabelCandidateKind",
TriggerSuggest:      false,
},
},
IsComplete: false,
}
--- FAIL: TestDecoder_CandidateAtPos_incompleteLabels (0.00s)
``` …
> Make sure limited label candidates are sorted

- decoder/code_lens.go
- decoder/decoder.go
- decoder/decoder_test.go
- decoder/hover.go
- decoder/path_reader.go
- decoder/reference_origins.go
- decoder/reference_origins_collect_hcl_test.go
- decoder/reference_origins_collect_json_test.go
- decoder/reference_origins_test.go
- decoder/reference_targets.go
- decoder/reference_targets_test.go
- decoder/semantic_tokens.go
- lang/path.go
- reference/origin.go
- reference/origin_local.go
- reference/origin_path.go
- reference/origins.go
- reference/origins_test.go
- reference/target.go
- reference/targets.go
- reference/targets_test.go
- reference/traversal.go
- reference/traversal_test.go
- schema/address.go
- schema/attribute_schema.go
- schema/block_schema.go
- schema/block_schema_test.go
- schema/path_target.go
This PR introduces a concept of a path-based origin, i.e. origin reference that is pointing to a different path, in Terraform that would be outside of a module.
In Terraform this can be represented by a module input name, pointing to the relevant variable, e.g.
```hcl
module "example" {
source = "./module"
foo = "bar"
}
```
where `foo` would be the `PathOrigin` and point to this block within `./module/`
```hcl
variable "foo" {
type = string
}
```
Relatedly all the existing origins become `LocalOrigin` with all the same existing structure.
There were a few high-level API changes in that both reference-lookup-related methods were moved under `Decoder` (from `PathDecoder`) as they can now both return results outside the context of a single path and therefore also need access to other paths …
> Introduce LocalOrigin + PathOrigin & schema.PathTarget

- decoder/reference_origins.go
- reference/origins.go
- reference/origins_test.go
As demonstrated by the attached test the implementation would previously fail to check the path before comparing local origins against local targets, which would result in cross-path references being matched when they're in fact only local.
> fix: matching of PathOrigins

- decoder/expression_candidates.go
- decoder/expression_candidates_test.go
As demonstrated by the attached test this fixes a case of completion of references where we intend to filter out external self-references to the outer block itself when the completion is requested within the block. Previously we'd only be comparing the range of completion and reference, without considering the filename.
Related: https://github.com/hashicorp/terraform-ls/issues/646
> fix: filtering of self references for cross-file references

- decoder/semantic_tokens.go
Fixes #108 
Nested dependent blocks no longer inherit the top level modifiers.
The examples used a custom VS Code theme:
```json
{
"name": "Example Theme",
"semanticHighlighting": true,
"semanticTokenColors": {
"hcl-blockType.terraform-resource": {"fontStyle": "bold", "foreground": "#fff"},
"hcl-blockType.terraform-data": {"fontStyle": "bold", "foreground": "#fff"},
"hcl-blockType.terraform-module": {"fontStyle": "bold", "foreground": "#3d5aff"},
"hcl-blockLabel.terraform-module.terraform-name": {"foreground": "#bac4ff"},
"hcl-blockLabel.terraform-type": {"foreground": "#844FBA", "fontStyle": "bold"},
"hcl-blockLabel.terraform-resource.terraform-name": {"foreground": "#a589b3"}
}
}
```
> fix: avoid semantic token modifier inheritance for dependent bodies

- decoder/dependent_body_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_test.go
- lang/semantic_token.go
- schema/attribute_schema.go
- schema/block_schema.go
- schema/label_schema.go
This is to enable https://github.com/hashicorp/terraform-schema/issues/96
---
The PR introduces a number of changes:
- `SemanticTokenModifier` in `LabelSchema` becomes plural, allowing assignment of more than 1 modifier via schema
- `SemanticTokenModifier` in `BlockSchema` becomes plural, allowing assignment of more than 1 modifier via schema (this actually remains unused downstream in https://github.com/hashicorp/terraform-schema/pull/100 but it's mostly just to align the API and make it more flexible 🤷🏻 
- Introduce `SemanticTokenModifiers` to `AttrSchema` such that we can use it downstream to report dependent attributes and later for adding any more modifiers per https://github.com/hashicorp/terraform-ls/issues/835
- Removes auto-assignment of the dependent modifier, to apply the …
> schema: Make modifiers plural in LabelSchema

- decoder/decoder.go
- decoder/reference_origins.go
- decoder/reference_targets.go
- decoder/reference_targets_test.go
- reference/origin.go
- reference/origin_direct.go
- reference/origins.go
- reference/origins_test.go
- reference/targets_test.go
- schema/body_schema.go
This PR allows schemas to introduce a target for the module source attribute. We achieve this by introducing a new field `Targets` to the `BodySchema`.
Example within terraform-schema: https://github.com/hashicorp/terraform-schema/pull/101
Required for https://github.com/hashicorp/terraform-ls/issues/558
> Expose new kind of origins

- decoder/decoder.go
- decoder/links.go
- decoder/links_test.go
Required for https://github.com/hashicorp/vscode-terraform/issues/673
This PR extends the collection of links inside a file from just blocks to attributes. With the change it's now possible to have an attribute (like `source` inside a module block) link to documentation.
> Enable DocsLink for attributes

- decoder/reference_origins.go
After running into this a couple of times [recently](https://github.com/hashicorp/hcl-lang/runs/7543556000?check_suite_focus=true), this PR now sorts the reference origins by path, filename and range.
Closes https://github.com/hashicorp/hcl-lang/issues/101
> Sort reference origins

- decoder/body_candidates_test.go
- decoder/candidates.go
- decoder/candidates_test.go
- decoder/completion_resolve.go
- decoder/context.go
- decoder/decoder_test.go
- decoder/expression_candidates.go
- decoder/expression_candidates_test.go
- decoder/label_candidates_test.go
- lang/candidate.go
- lang/completion.go
- schema/attribute_schema.go
- schema/body_schema.go
This PR extends the completion of attribute values by getting completion candidates from dynamically registered hooks.
If an attribute schema contains one (or multiple) completion hooks, we look in the global decoder context to see if those hooks are registered. If they are, each hook is executed and should return a list of completion candidates.
The resulting candidate always replaces the whole attribute value range (including quotes).
---
* Part of https://github.com/hashicorp/terraform-ls/issues/868
> Enable hooks for dynamic completion

- decoder/context.go
- decoder/expression_candidates.go
- decoder/expression_candidates_test.go
- lang/candidate.go
This PR adds the `SortText` field to completion candidates and only allows `maxCandidates` (100 for now) to be returned on attribute expression completion.
We stop adding candidates and executing hooks once the limit is reached. A better way might be to allow each hook to contribute to the list of completion candidates.
> Add `SortText` and respect `maxCandidates` for hook completion

- decoder/expression_candidates.go
Those helpers can be used to test hooks downstream
> Expose completion path keys for testing

- .github/workflows/ci.yml
This PR updates our workflows to make `setup-go` obtain the Go version directly from the `.go-version` file.
> Update `setup-go` to obtain version via `go-version-file`

- decoder/body_candidates.go
- decoder/body_extensions_test.go
- decoder/candidates.go
- decoder/candidates_test.go
- decoder/decoder.go
- decoder/expression_candidates.go
- decoder/hover.go
- decoder/hover_test.go
I'd love to attach some screenshots before & after, but all usage of the extensions currently involves `DependentBody` which itself has some bugs, which are being fixed as part of https://github.com/hashicorp/hcl-lang/pull/142/commits/32e493e09ce61eca33e4fa2176e943ac599a9015 in https://github.com/hashicorp/hcl-lang/pull/142
So failing & passing tests will hopefully suffice.
> decoder: fix completion & hover for `count` extension value

- decoder/body_candidates.go
- decoder/body_extensions_test.go
- decoder/candidates.go
- decoder/decoder.go
- decoder/expression_candidates.go
- decoder/hover.go
- decoder/hover_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_test.go
- schema/body_schema.go
- schema/schema.go
This provides completion hints inside blocks for `for_each` and `each.*` references within `resource`, `data` and `module` blocks anywhere the `for_each` meta-argument is supported. It detects if `for_each` is used already and does not suggest duplicates and detects when it is necessary to provide `each.*` completions. This does not complete the values for `each.key` and `each.value`, e.g. `each.value.something`.
This also provides hover support for `for_each` and `each.*` references using the documentation as source.
This also provides semantic token support for `for_each` and `each.*` references.
Closes https://github.com/hashicorp/terraform-ls/issues/861
> Implement for_each and each.* completion, hover info, and semantic tokens

- decoder/expression_candidates.go
- decoder/hover.go
- decoder/reference_targets.go
- decoder/semantic_tokens.go
- lang/address.go
- reference/origins.go
- reference/target.go
- reference/targets.go
- reference/targets_test.go
This PR intended to be no-op for the end-user.
It introduces the concept of "local references", which can be utilised for `count.index`, `each.*` and `self.*` references, as drafted within https://github.com/hashicorp/hcl-lang/pull/149
While there are tests attached, there is no code actually collecting such local targets - that is left for follow-up PRs which can be made out of the linked PR.
It also leaves out the question of rendering such reference targets. Now that there can be two ways of referring to the same target, there can be some contexts where it is appropriate to use one address over the other, and vice versa. I could not find any way to solve that problem in an abstract sense which would work for all three use cases. So I left this for the follow-up PRs. I did however leave …
> Add support for local reference targets

- decoder/body_candidates.go
- decoder/body_extensions_test.go
- decoder/candidates.go
- decoder/decoder.go
- decoder/hover.go
- decoder/hover_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_test.go
- schema/body_schema.go
- schema/schema.go
Adds support for completion of dynamic blocks in resource, data, provider and provisioner blocks.
This does not provide completion for the label for a given dynamic block, which will be provided in a future set of work.
Partially implements https://github.com/hashicorp/terraform-ls/issues/530
> Support Dynamic block expression extensions

- decoder/hover.go
- decoder/hover_expressions_test.go
- decoder/hover_test.go
This change ensures that we only use the collected origins when matching targets on hover. So whenever we decide not to collect an origin during collection, the hover logic will also exclude it.
> Refactor `hoverAtPos` to use collected origins

- reference/target.go
- reference/targets_test.go
As the in-line comment explains, previously we'd try to "shorten" the origin address by actually "growing" it.
In theory this could have happened prior to https://github.com/hashicorp/hcl-lang/pull/150 but it apparently never did, or nobody reported it. It would require an origin with less segments than the compared target. In most (all?) cases, the targets have at least 2 segments and so that would require comparison with a single-segment origin, such as `foo`. This was also additionally gated by another condition, which was somewhat naively modified to account for local addresses and that condition is no longer necessary now.
> reference: Fix panic when trying to shorten origin address

- reference/target.go
- reference/targets_test.go
As the test shows, we'd previously consider `TargetableFromRangePtr` mismatch as complete mismatch, even though the same target could be a match using the absolute address.
Mostly for convenience in test, the implementation treats `TargetableFromRangePtr: nil` as an automatic match, but I can be convinced to change that, if we deem it's a bad idea.
> reference: Fix matching for targets which involve ranges & both addresses

- decoder/expression_candidates.go
- decoder/hover.go
- reference/target.go
- reference/targets.go
- reference/targets_test.go
This introduces some minor changes to the interfaces, to plumb context through, in preparation for using it to pass down context, such as whether "SelfRefs" is active, i.e. whether `self.*` addresses are relevant in that context.
Additionally, the matching logic is being refactored and updated to account for cyclical references, specifically to continue **rejecting** completion such as
```hcl
resource "aws_instance" "test" {
count = 4
cpu_core_count = aws_instance.test.cpu_core_count
}
```
**TODO**: Address hover & semtok highlighting which still _recognize_ the above as valid ^
and
```hcl
resource "aws_instance" "test" {
count = count.index
}
```
and (future)
```hcl
resource "aws_instance" "test" {
ami = self.ami
}
```
> reference: refactor & fix matching of cyclical refs

- decoder/body_extensions_test.go
- decoder/decoder.go
- decoder/expression_candidates.go
- decoder/hover.go
- decoder/hover_test.go
- decoder/reference_targets.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_test.go
Depends on #159 
--- 
This PR changes collection of reference targets, such that we now collect `count.index` as a target to the `count` attribute. This in turn enables go-to-definition and go-to-references between `count` and `count.index`.
Additionally, it updates completion, hover and semantic tokens, to make use of this reference target and just treat it like any other valid reference.
Lastly I updated the description of the `count` attribute to reflect what it does and also add the note about conflict we already have in the `for_each` description.
---
> Use local ref. targets for `count.index`

- decoder/body_extensions_test.go
- decoder/decoder.go
- decoder/expression_candidates.go
- decoder/hover.go
- decoder/hover_test.go
- decoder/reference_targets.go
This PR changes collection of reference targets, such that we now collect `each.key` and `each.value` as targets to the `for_each` attribute. This in turn enables go-to-definition and go-to-references between `for_each` and the two references.
Additionally, it updates completion, hover and semantic tokens, to make use of these reference targets and just treat them like any other valid reference.
---
> Use local ref. targets for `each.*` references

- decoder/body_extensions_test.go
- decoder/candidates.go
- decoder/expression_candidates.go
- decoder/hover.go
- decoder/reference_origins.go
- decoder/reference_targets.go
- decoder/reference_targets_collect_extensions_hcl_test.go
- decoder/reference_targets_collect_hcl_test.go
- decoder/reference_targets_collect_json_test.go
- reference/target.go
- reference/target_test.go
- reference/targets.go
- reference/targets_test.go
- reference/traversal.go
- reference/traversal_test.go
- schema/block_schema.go
- schema/body_schema.go
- schema/schema.go
Originally the hope/plan was to have just a single "flag" in the schema under the `Extensions` - `SelfRef: true`, just like we have for Count and ForEach and will have for dynamic blocks. However, it turns out that isn't most practical. This is because we collect reference targets with the appropriate addresses separately from origins and because we would have to traverse through the rest of a potentially deeply nested and long block, to find out whether a particular target needs a local `self` address or not.
So we instead introduce the additional `DependentBodySelfRef: true` which implies that any attributes and blocks within the body will be collected as a target with an additional `self.*` local address. This will then be enabled for Terraform within the `resource` and `data` blocks …
> Introduce support for `self.*` references

- decoder/body_candidates.go
- decoder/body_extensions_test.go
- decoder/candidates.go
- decoder/decoder.go
- decoder/hover.go
- decoder/hover_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_test.go
- schema/schema.go
This PR enables the next stage for dynamic block completion. Based on the blocks of a dependent body, we can now complete the label for `dynamic` blocks based on the available block names and the block-related attributes in the `content` block. It works for nested blocks, too.
--- 
In nested blocks
> Enable dynamic label completions

- decoder/body_extensions_test.go
- decoder/decoder.go
This PR fixes an error where we're offering static blocks for completion when there are no blocks in the dependent body.
`dynamic` isn't available anymore, because there are no blocks in the dependent body.
> Avoid completing static block inside a `dynamic` label

- decoder/hover_test.go
- decoder/reference_origins.go
This PR adds the extension-based schema changes for `count` and `for_each` during reference origin collection. This error occurred because we collected no origins for `var.name`.
> Fix missing hover for `count` and `for_each` expression

- decoder/body_extensions_test.go
- decoder/decoder.go
- decoder/hover_test.go
This PR removes `schema.BlockTypeMap` from the `dynamic` block
> Change dynamic block type to default

- decoder/expr_any.go
- decoder/expression.go
- decoder/expression_candidates.go
- decoder/expression_test.go
- decoder/hover.go
- decoder/reference_origins.go
- decoder/reference_targets.go
- decoder/semantic_tokens.go
- schema/constraint_any_expression.go
- schema/constraint_test.go
This is a small update to #177 and enables access to path context, which is required for working with functions, references and origins.
> Refactor `NewExpression` to allow access to path context

- decoder/expr_list.go
- decoder/expr_map.go
- decoder/expr_object.go
- decoder/expr_one_of.go
- decoder/expr_set.go
- decoder/expr_tuple.go
- decoder/expression.go
This is primarily to make it easier to "hand-over" completion/hover/etc. between different expression types (which do not /need to/ have access to all of `PathDecoder`) and reduce diff conflicts between upcoming PRs where each involves different expression type.
It is expected that all complex types (list, set, tuple, map, object) _may_ contain either `Reference` (hence need `ReferenceTargets`) or `AnyExpression` (hence need future `FunctionsMap` and possibly `ReferenceTargets` too).
I have briefly considered creating a separate type, e.g. `ExpressionContext` or pass these things via `context.Context`, or use the static `newExpression()` in all places where `(*PathDecoder) newExpression()` is now used,  but concluded that it would all be premature optimization at this point.
> decoder: Refactor `newExpression()` & plumb `PathContext`

- decoder/expression.go
- decoder/expression_candidates.go
This helper is expected to be used in completion for most constraints.
I am still not fully confident it covers all cases - as explained in the comment, but I do believe it deserves to be extracted.
> decoder: Extract & document `isEmptyExpression()`

- decoder/expr_keyword.go
- decoder/expr_literal_value.go
- decoder/expr_type_declaration.go
- decoder/expr_unknown.go
- decoder/expression.go
- decoder/reference_origins.go
- decoder/reference_targets.go
This better aligns with a convention of minimal interfaces in Go, also surfaced as a [Go Proverb](https://go-proverbs.github.io/) ["The bigger the interface, the weaker the abstraction."](https://www.youtube.com/watch?v=PAAkCSZUG1c&t=5m17s) and exemplified throughout the stdlib, e.g. in the [`io/fs.FS`](https://pkg.go.dev/io/fs#FS) interface and [friends](https://pkg.go.dev/io/fs#ReadDirFS).
Another (AFAIK unwritten) convention is to suffix such interface types with `-er` (e.g. `io.Writer`, `io.Reader`), but as shown on the `fs` interfaces, this isn't always practical and IMO wouldn't be in our case.
To my best knowledge all types we have bootstrapped currently _would_ still need to provide completion, hover and semantic tokens, so I'm keeping these in the base interface.
> decoder: Make reference collection optional for Expression

- decoder/expr_any.go
- decoder/expr_list.go
- decoder/expr_literal_type.go
- decoder/expr_map.go
- decoder/expr_object.go
- decoder/expr_one_of.go
- decoder/expr_reference.go
- decoder/expr_set.go
- decoder/expr_tuple.go
- decoder/expression.go
- decoder/expression_test.go
- decoder/reference_targets.go
- schema/attribute_schema.go
- schema/block_schema.go
As discovered while implementing this method for `List`
- https://github.com/hashicorp/hcl-lang/pull/195
we will need to pass around an address which may not necessarily refer to the attribute as whole, but different expressions depending on levels of nesting.
This is expected to be useful for most other constraints which can have reference targets inside (e.g. `Object` or `Map`).
This also adds some compilation-time tests to ensure that we don't accidentally change interface somewhere and "turn off" collection of origins or targets.
> decoder: Adjust `Expression.ReferenceTargets()` address arguments

- decoder/expr_keyword.go
- decoder/expr_keyword_completion.go
- decoder/expr_keyword_completion_test.go
- decoder/expr_keyword_hover.go
- decoder/expr_keyword_hover_test.go
- decoder/expr_keyword_semtok.go
- decoder/expr_keyword_semtok_test.go
- schema/constraint_keyword.go
--- 
https://github.com/hashicorp/terraform-schema/pull/174/commits/442c5c891f5798d4a345f8ff55ba1ccb90fec129 is downstream reflection of this constraint. The examples below leverage that commit. It also however makes it clear that `Keyword` often in schema relies on `OneOf` constraint, so for full support of keywords, that constraint has to be implemented.
Since keywords aren't nested, this is expected to be no-op for the end-user and essentially just work the same as before.
> decoder/schema: Add support for `Keyword` as `Constraint`

- decoder/expression_candidates.go
- decoder/hover.go
- decoder/reference_origins.go
- reference/target.go
- reference/targets.go
- reference/targets_test.go
- reference/traversal.go
- reference/traversal_test.go
While working on https://github.com/hashicorp/hcl-lang/pull/185 I noticed that there's a number of functions which still accept the "legacy" `schema.TraversalExpr` and these will need to be rewritten for `schema.Reference`.
In preparation for that, and to keep the existing functions working, I am proposing some name changes in this PR.
> Deprecate old reference matching logic

- decoder/reference_targets.go
- decoder/reference_targets_collect_extensions_json_test.go
Sometimes, we create local addresses with `nil` steps, and the LS crashes when iterating over those. This PR aims to fix that.
We don't get a body range for JSON-based configuration files, so we can never set the `TargetableFromRangePtr` for collected targets. 
https://github.com/hashicorp/hcl-lang/blob/4804a1caffd2d165978b0dc75ca4df6bd6ada14e/decoder/reference_targets.go#L687-L689
Without this pointer, we can't build a local address. So instead of trying to be clever and set a specific length, we now create all local addresses with a zero length.
Fixes https://github.com/hashicorp/vscode-terraform/issues/1338
Fixes https://github.com/hashicorp/terraform-ls/issues/1157
> Fix `LocalAddr` creation in target collection for JSON files

- decoder/path_context.go
- schema/signature.go
This PR extracts the function signature types from #135 to enable us to implement upstream changes in terraform-schema before completing the function signatures features as a whole.
We can use the new signature types to embed function signatures in terraform-schema.
---
* Part of https://github.com/hashicorp/terraform-ls/issues/37
> Add function signature types

- decoder/expr_any.go
- decoder/expr_list.go
- decoder/expr_literal_type.go
- decoder/expr_map.go
- decoder/expr_object.go
- decoder/expr_one_of.go
- decoder/expr_reference.go
- decoder/expr_tuple.go
- decoder/expression.go
- decoder/reference_targets.go
The new interface better reflects a scenario where expression can be targeted by itself, but not the attribute. In Terraform this may occur in `required_providers` > `configuration_aliases` where entries are targetable provider names, but configuration_aliases attribute is not.
In that ^ scenario the expected schema would be e.g.
```go
"configuration_aliases": &schema.AttributeSchema{
Constraint: schema.Set{
Elem: schema.Reference{
Address: &schema.ReferenceAddrSchema{
ScopeId: refscope.ProviderScope,
},
Name: "provider",
},
},
},
},
```
i.e. there would be no `Address` set on the `AttributeSchema`.
I renamed `AddressContext` to `TargetContext` as per earlier discussion in a different PR about lots of things called "address". Hopefully this is a better name 🤞🏻 
Finally, the change in …
> decoder: Adjust `Constraint`.`ReferenceTargets` method args

- decoder/reference_targets.go
- schema/constraint_type_declaration.go
This was forgotten in the big diff of https://github.com/hashicorp/hcl-lang/pull/177
It is the reason why `var.*` reference targets collected for `variable` blocks in https://github.com/hashicorp/hcl-lang/pull/183 get collected as `dynamic` (unknown/any type).
I also left a note about optional object attributes as that will be implemented as part of https://github.com/hashicorp/terraform-ls/issues/917
> decoder: reflect `Constraint` when collecting `AsTypeOf` reference targets

- schema/constraint.go
- schema/constraint_list.go
- schema/constraint_literal_type.go
- schema/constraint_literal_value.go
- schema/constraint_map.go
- schema/constraint_object.go
- schema/constraint_set.go
- schema/constraint_test.go
- schema/constraint_tuple.go
Similar to the existing `EmptyCompletionData()`, in some contexts it feels more appropriate to display something more helpful than just short "friendly name" for the type.
The friendly name is still relevant to display e.g. next to the completion item, where there is no space for more details.
We could potentially use this also when displaying hover for attributes, where we currently use just `FriendlyName()`, but I'd leave that for another discussion later.
The aim is to be able to mimic the existing hover data for complex `LiteralType` constraints.
I also used the pointer (`*HoverData`) just so that we could also still decide at runtime in each constraint whether or not to return hover data. This is because e.g.`List` or `Set` may behave differently depending on the Constraints of its …
> schema: Introduce `EmptyHoverData()` to `Constraint`

- decoder/expression.go
- decoder/expression_test.go
This PR introduces two small helper functions decoupled from a few discovered use cases / PRs:
- https://github.com/hashicorp/hcl-lang/pull/183 (for `object({ ... })`)
- https://github.com/hashicorp/hcl-lang/pull/186 (through `Object` or `Map`)
- https://github.com/hashicorp/hcl-lang/pull/199
- https://github.com/hashicorp/hcl-lang/pull/203
- it's also expected to be useful in `AnyExpression` constraint
The last attached test case illustrates an example of the problem.
--- 
Our use cases don't _actually_ involve multi-byte runes, so in theory we could be just comparing single bytes and avoid the decoding, but that then makes the consumer side a bit more verbose since `'\n'` would need to be written e.g. as `byte('\n')`. We could technically allow runes and treat them like single bytes, …
> decoder: Introduce helper functions for completion inside `ObjectConsExpr`

- schema/constraint.go
- schema/constraint_list.go
- schema/constraint_literal_type.go
- schema/constraint_literal_value.go
- schema/constraint_map.go
- schema/constraint_object.go
- schema/constraint_set.go
- schema/constraint_tuple.go
When rendering parts of hover data, esp. for constraints which are likely to span multiple lines and contain more nested constraints under them (e.g. objects), it is useful to produce hover data which are already correctly nested according to the parent expression.
This aligns with how we render hover data currently in https://github.com/hashicorp/hcl-lang/blob/6302afc62e3512cd825e75d3f8c1e7c162c31548/decoder/hover.go#L478-L555
> schema: Introduce `nestingLevel` to `Constraint`.`EmptyHoverData()`

- decoder/expression.go
- decoder/expression_test.go
As per in-line comment:
```go
// rawObjectKey extracts raw key (as string) from KeyExpr of
// any hclsyntax.ObjectConsExpr along with the corresponding range
// and boolean indicating whether the extraction was successful.
```
This is expected to be used in any expression type that involves `ObjectConsExpr`, i.e.
- https://github.com/hashicorp/hcl-lang/pull/203
- https://github.com/hashicorp/hcl-lang/pull/199
- https://github.com/hashicorp/hcl-lang/pull/183
for validating keys before reporting them as semantic tokens, or to isolate the unquoted part which in turn enables validation/lookup of the attribute name in case of an object. Range then allows us to also extract the prefix for any necessary filtering when doing completion for the whole attribute.
> decoder: Introduce rawObjectKey to extract raw keys

- decoder/expression_candidates.go
- schema/constraint.go
- schema/constraint_any_expression.go
- schema/constraint_list.go
- schema/constraint_literal_type.go
- schema/constraint_literal_value.go
- schema/constraint_map.go
- schema/constraint_object.go
- schema/constraint_set.go
- schema/constraint_test.go
- schema/constraint_tuple.go
As illustrated by the diff and some conversation in the original PR https://github.com/hashicorp/hcl-lang/pull/177#issuecomment-1376190653 the plan was for `Comparable` to allow completion hooks to tell whether the constraint is string-compatible (and potentially other type compatible later).
One more use case / problem emerged where we'll need to collect `Object` or `Map` (or `Set`, `List`, `Tuple`) as type-aware reference targets (assuming we intend to use them also as part of `LiteralType` and `LiteralValue`) and we need to know the corresponding type of the nested element/attribute.
--- 
I originally had the interface like this
```go
type TypeAwareConstraint interface {
ConstraintType() cty.Type
}
```
until I realised that this just won't work e.g. for `OneOf` which can only determine …
> schema: Replace `Comparable` w/ `TypeAwareConstraint`

- decoder/expression.go
- decoder/reference_targets.go
This uncovered another part of the codebase which was yet to be adapted to `Constraint`s, which is collection of inferred targets, i.e. targets which have their address inferred from the parent block, as opposed explicitly within the attribute schema.
In addition to the introduction of the new fields, the reference target collection logic is being updated in a backwards-compatible way.
> decoder: Introduce `ParentLocalAddress` to `TargetContext`

- decoder/attribute_candidates.go
- decoder/label_candidates.go
- schema/constraint.go
- schema/constraint_any_expression.go
- schema/constraint_keyword.go
- schema/constraint_list.go
- schema/constraint_literal_type.go
- schema/constraint_literal_value.go
- schema/constraint_map.go
- schema/constraint_object.go
- schema/constraint_one_of.go
- schema/constraint_reference.go
- schema/constraint_set.go
- schema/constraint_tuple.go
- schema/constraint_type_declaration.go
While trying to implement `EmptyCompletionData()` for `Object` and `Map`, I realised that in both cases the constraint may be nested, i.e. the object may be nested under another object/map. In that scenario we need to render the right indentation depending on the nesting level we're at.
The updated interface accounts for this.
> schema: Introduce `nestingLevel` to EmptyCompletionData()

- schema/constraint_any_expression.go
- schema/constraint_list.go
- schema/constraint_map.go
- schema/constraint_object.go
- schema/constraint_one_of.go
- schema/constraint_set.go
- schema/constraint_test.go
- schema/constraint_tuple.go
We could add tests, but in all cases it's either simple pass of an existing type (1LOC) or just putting the same data into a different shape, so I'm not sure it's worth testing in isolation.
We can still test it indirectly as part of reference target collection.
> schema: Implement `ConstraintType()` for all remaining constraints

- decoder/expr_one_of.go
- decoder/expr_one_of_completion.go
- decoder/expr_one_of_completion_test.go
- decoder/expr_one_of_hover.go
- decoder/expr_one_of_hover_test.go
- decoder/expr_one_of_ref_origins.go
- decoder/expr_one_of_ref_origins_test.go
- decoder/expr_one_of_ref_targets.go
- decoder/expr_one_of_ref_targets_test.go
- decoder/expr_one_of_semtok.go
- decoder/expr_one_of_semtok_test.go
- schema/constraint_one_of.go
> decoder/schema: Add support for `OneOf` as `Constraint`

- schema/constraint_list.go
- schema/constraint_literal_type.go
- schema/constraint_literal_value.go
- schema/constraint_map.go
- schema/constraint_object.go
- schema/constraint_set.go
- schema/constraint_test.go
- schema/constraint_tuple.go
The implementation for `LiteralValue` specifically turns out to be a little more involved than I originally hoped, but I decided to include it in the PR as well.
It reminds me that implementing https://github.com/hashicorp/hcl-lang/pull/187 may be more involved in general, but we can cross the bridge when we come to it.
The primary motivation to get this PR out was to enable more comprehensive testing of hover in https://github.com/hashicorp/hcl-lang/pull/203
> schema: Implement `EmptyHoverData()` for all constraints

- schema/constraint.go
- schema/constraint_keyword.go
- schema/constraint_list.go
- schema/constraint_literal_type.go
- schema/constraint_literal_value.go
- schema/constraint_map.go
- schema/constraint_object.go
- schema/constraint_one_of.go
- schema/constraint_set.go
- schema/constraint_test.go
- schema/constraint_tuple.go
- schema/constraint_type_declaration.go
Aside from reviewing the attached unit tests, this can also be tested when combined with https://github.com/hashicorp/terraform-schema/pull/174
There are two contexts in which `EmptyCompletionData()` is used, as shown below.
> schema: Implement `EmptyCompletionData()` for all constraints

- decoder/expr_set.go
- decoder/expr_set_completion.go
- decoder/expr_set_completion_test.go
- decoder/expr_set_hover.go
- decoder/expr_set_hover_test.go
- decoder/expr_set_ref_origins.go
- decoder/expr_set_ref_targets.go
- decoder/expr_set_semtok.go
- decoder/expr_set_semtok_test.go
- schema/constraint_set.go
- schema/constraint_test.go
> decoder: Add support for `Set` as `Constraint`

- decoder/expr_list.go
- decoder/expr_list_completion.go
- decoder/expr_list_completion_test.go
- decoder/expr_list_hover.go
- decoder/expr_list_hover_test.go
- decoder/expr_list_ref_origins.go
- decoder/expr_list_ref_targets.go
- decoder/expr_list_semtok.go
- decoder/expr_list_semtok_test.go
- schema/constraint_list.go
- schema/constraint_test.go
Depends on https://github.com/hashicorp/hcl-lang/pull/196
--- 
---
> decoder: Add support for `List` as `Constraint`

- decoder/expr_tuple.go
- decoder/expr_tuple_completion.go
- decoder/expr_tuple_completion_test.go
- decoder/expr_tuple_hover.go
- decoder/expr_tuple_hover_test.go
- decoder/expr_tuple_ref_origins.go
- decoder/expr_tuple_ref_targets.go
- decoder/expr_tuple_semtok.go
- decoder/expr_tuple_semtok_test.go
- schema/constraint_test.go
- schema/constraint_tuple.go
> decoder: Add support for `Tuple` as `Constraint`

- decoder/attribute_candidates.go
- decoder/body_candidates.go
- decoder/candidates.go
- decoder/expr_list_completion.go
- decoder/expr_map_completion.go
- decoder/expr_object.go
- decoder/expr_set_completion.go
- decoder/expr_tuple_completion.go
- decoder/expression_test.go
- decoder/label_candidates.go
- schema/constraint.go
- schema/constraint_any_expression.go
- schema/constraint_keyword.go
- schema/constraint_list.go
- schema/constraint_literal_type.go
- schema/constraint_literal_value.go
- schema/constraint_map.go
- schema/constraint_object.go
- schema/constraint_one_of.go
- schema/constraint_reference.go
- schema/constraint_set.go
- schema/constraint_test.go
- schema/constraint_tuple.go
- schema/constraint_type_declaration.go
It was discovered while implementing https://github.com/hashicorp/hcl-lang/pull/203 that `schema.Object.EmptyCompletionData()` _always_ pre-fills _all_ attributes, which is undesirable.
- if we need to pre-fill any attributes, it should only be the required ones, not all
- pre-filling attributes has historically been gated via `PrefillRequiredFields`, and this should be reflected in objects as well
I also did a little bit of refactoring to (hopefully) make the code more readable, in spite of the additional complexity.
All commits are also part of https://github.com/hashicorp/hcl-lang/pull/203 but I decoupled them here to make it easier to review.
--- 
This will also enable us to later customise the existing literal type/value pre-filling like `attr = "value"` or `attr = false` - maybe put …
> decoder/schema: Pass `PrefillRequiredFields` around via context

- decoder/signature.go
- decoder/signature_test.go
- lang/signature.go
- schema/signature.go
This PR adds the `SignatureAtPos` method to enable support for signature help. Function signatures must be present in the path context for it to work. We added the function signatures to terraform-schema in https://github.com/hashicorp/terraform-schema/pull/145. 
If you want to try it, there is a draft PR in terraform-ls, tying it all together: https://github.com/hashicorp/terraform-ls/pull/1077
Nested function calls with variadic parameters
Functions without any arguments
No signature help, if passing too many arguments
Multiline function calls
---
* Part of https://github.com/hashicorp/terraform-ls/issues/37
> Add support for `SignatureAtPos`

- decoder/expr_literal_type.go
- decoder/expr_literal_type_completion.go
- decoder/expr_literal_type_completion_test.go
- decoder/expr_literal_type_hover.go
- decoder/expr_literal_type_hover_test.go
- decoder/expr_literal_type_ref_targets.go
- decoder/expr_literal_type_semtok.go
- decoder/expr_literal_type_semtok_test.go
- decoder/expression.go
- decoder/expression_test.go
- decoder/hover.go
- schema/attribute_schema.go
- schema/attribute_schema_legacy_test.go
- schema/attribute_schema_test.go
- schema/constraint_literal_type.go
--- 
Existing tests were updated as part of https://github.com/hashicorp/hcl-lang/commit/699069384a9c1ef08b7b7a7ab9e8cd6eb8ac739b (not part of this PR) and yield either comparable or better results, except for reference collection, which:
- we agreed to leave for a separate PR
- involves other constraints which aren't implemented yet
---
> decoder: Add support for `LiteralType` as `Constraint`

- decoder/expr_reference.go
- decoder/expr_reference_completion.go
- decoder/expr_reference_completion_test.go
- decoder/expr_reference_hover.go
- decoder/expr_reference_hover_test.go
- decoder/expr_reference_ref_origins.go
- decoder/expr_reference_ref_origins_test.go
- decoder/expr_reference_ref_targets.go
- decoder/expr_reference_ref_targets_test.go
- decoder/expr_reference_semtok.go
- decoder/expr_reference_semtok_test.go
- decoder/expression.go
- reference/target.go
- reference/targets.go
- reference/traversal.go
- schema/constraint_reference.go
--- 
There is quite a lot of logic related to reference collection, which I am not touching in this PR. That will be addressed more broadly as part of https://github.com/hashicorp/hcl-lang/pull/239 I did however go through all the related legacy tests and made sure they pass (when using `schema.Reference`) in combination with this PR.
The updated tests are in https://github.com/hashicorp/hcl-lang/commit/c0a2da2fe7f45573798860481d1f62bb363e4407
---
> decoder: Add support for `Reference` as `Constraint`

- decoder/expr_list_ref_origins.go
- decoder/expr_list_ref_origins_test.go
- decoder/expr_map_ref_origins.go
- decoder/expr_map_ref_origins_test.go
- decoder/expr_object_ref_origins.go
- decoder/expr_object_ref_origins_test.go
- decoder/expr_one_of_ref_origins.go
- decoder/expr_one_of_ref_origins_test.go
- decoder/expr_set_ref_origins.go
- decoder/expr_set_ref_origins_test.go
- decoder/expr_tuple_ref_origins.go
- decoder/expr_tuple_ref_origins_test.go
- decoder/expression.go
- decoder/expression_test.go
- reference/origin.go
- reference/origin_local.go
- reference/origin_path.go
This partially addresses https://github.com/hashicorp/hcl-lang/issues/228
--- 
Legacy tests were updated in 7c88045f9e0fdeba4a7b62244f6151119a8b8579
--- 
Unfortunately most of the code is pretty much no-op on the UX side of things without https://github.com/hashicorp/hcl-lang/pull/239 - i.e. there isn't much to demo here. The updated legacy tests + new tests hopefully prove that it's working well though!
> Finish reference origin collection for all constraints

- decoder/expr_list_ref_targets.go
- decoder/expr_list_ref_targets_test.go
- decoder/expr_literal_type.go
- decoder/expr_literal_type_ref_targets.go
- decoder/expr_literal_type_ref_targets_test.go
- decoder/expr_map_ref_targets.go
- decoder/expr_map_ref_targets_test.go
- decoder/expr_object_ref_targets.go
- decoder/expr_object_ref_targets_test.go
- decoder/expr_one_of.go
- decoder/expr_one_of_ref_targets_test.go
- decoder/expr_reference_ref_targets.go
- decoder/expr_reference_ref_targets_test.go
- decoder/expr_set_ref_targets.go
- decoder/expr_set_ref_targets_test.go
- decoder/expr_tuple_ref_targets.go
- decoder/expr_tuple_ref_targets_test.go
- decoder/expression.go
- decoder/expression_test.go
- decoder/reference_targets.go
- decoder/reference_targets_collect_hcl_test.go
- schema/attribute_schema_test.go
- schema/constraint_reference.go
Depends on https://github.com/hashicorp/hcl-lang/pull/241
Closes https://github.com/hashicorp/hcl-lang/issues/228
This excludes `LiteralValue`, but [we don't actually use that constraint in reference target context currently in `terraform-schema` anyway](https://github.com/search?q=repo%3Ahashicorp%2Fterraform-schema%20LegacyLiteralValue&type=code).
--- 
(requires https://github.com/hashicorp/hcl-lang/pull/241 and https://github.com/hashicorp/terraform-schema/pull/174 )
> Finish reference target collection for all constraints

- decoder/expr_literal_value.go
- decoder/expr_literal_value_completion.go
- decoder/expr_literal_value_completion_test.go
- decoder/expr_literal_value_hover.go
- decoder/expr_literal_value_hover_test.go
- decoder/expr_literal_value_semtok.go
- decoder/expr_literal_value_semtok_test.go
- decoder/expression_candidates.go
> decoder: Add support for `LiteralValue` as `Constraint`

- decoder/expr_reference_completion_test.go
- decoder/expression_candidates_legacy_test.go
- decoder/hover_expressions_legacy_test.go
- decoder/semantic_tokens_expr_legacy_test.go
- reference/target.go
- reference/targets_test.go
Terraform itself basically doesn't use cty's TestConformance, but instead uses the convert.Convert function. This makes the type comparison a lot more lenient, where it accepts basically any primitive type for any other. It does however reject mismatch between complex types.
Other products / language servers may benefit from the stricter comparison (as implemented by `TestConformance`) but we do not have enough data to understand this problem space and so we optimise for Terraform for now. This should not hurt other products unless they have a lot of references to filter. At worst they'll get *more* completion items and hover/semtokens for references which are not relevant, but should still get the ones which are relevant. They may also happen to implement type comparison same way as …
> reference: Update type matching to align w/ Terraform's

- schema/attribute_schema.go
This is to (a) avoid some unnecessary memory allocations and (b) make testing easier with `Constraint`, as discovered in https://github.com/hashicorp/terraform-schema/actions/runs/4621591413/jobs/8173199515#step:8:1184
> schema: Avoid creating empty `Expr` slice if `Constraint` is set

- decoder/expr_any.go
- decoder/expr_any_completion.go
- decoder/expr_any_completion_test.go
- decoder/expr_any_hover.go
- decoder/expr_any_hover_test.go
- decoder/expr_any_ref_origins.go
- decoder/expr_any_ref_origins_test.go
- decoder/expr_any_ref_targets.go
- decoder/expr_any_ref_targets_test.go
- decoder/expr_any_semtok.go
- decoder/expr_any_semtok_test.go
- decoder/expr_function.go
- decoder/expr_literal_type_completion.go
- decoder/expr_reference_ref_origins.go
- lang/candidate.go
- lang/candidate_kind_string.go
- lang/semantic_token.go
- reference/traversal.go
- schema/constraint_any_expression.go
- schema/constraint_literal_type.go
* Depends on https://github.com/hashicorp/hcl-lang/pull/246
--- 
We provide completion of references, function and literals for all expressions
Completion, hover and semantic tokens also work for nested expressions, like within objects or function calls.
---
* Part of https://github.com/hashicorp/terraform-ls/issues/496
* Part of https://github.com/hashicorp/terraform-ls/issues/37
> decoder: Add support for `AnyExpression` as `Constraint`

- decoder/expr_list_ref_targets.go
- decoder/expr_list_ref_targets_test.go
- decoder/expr_literal_type_ref_targets_test.go
- decoder/expr_map_ref_targets.go
- decoder/expr_map_ref_targets_test.go
- decoder/expr_object_ref_targets.go
- decoder/expr_object_ref_targets_test.go
- decoder/expr_set_ref_targets.go
- decoder/expr_set_ref_targets_test.go
- decoder/expr_tuple_ref_targets.go
- decoder/expr_tuple_ref_targets_test.go
- decoder/reference_targets.go
Previously, as part of https://github.com/hashicorp/hcl-lang/pull/239 we forgot about the fact that complex expression types, such as `List`, `Set`, `Tuple`, `Map` or `Object` may end up being collected as reference targets in a context where there is no corresponding config/expression.
This is currently surfaced in the UX by references to any complex types missing unless explicitly declared:
> Collect implied reference targets for complex types

- decoder/expr_any_completion_test.go
- decoder/expr_literal_type_completion.go
- decoder/expr_literal_type_completion_test.go
- decoder/expr_literal_value_completion.go
- decoder/expr_literal_value_completion_test.go
- decoder/expr_literal_value_hover.go
- decoder/expr_literal_value_hover_test.go
As discovered in https://github.com/hashicorp/hcl-lang/pull/251
`LiteralValue` constraint (prior to this patch) ignores `Description` and `IsDeprecated` fields during completion and hover.
> decoder: Reflect `LiteralValue` `Description` & `IsDeprecated` in completion/hover

- schema/constraint_literal_type.go
- schema/constraint_literal_type_test.go
As discovered in manual testing and in #251 
Completion of an attribute of `cty.Tuple` type would previously cause a crash.
I also decided to add some more tests to cover the (clearly non-trivial enough to hide a bug) `EmptyCompletionData()` method on `LiteralType`.
> fix(schema): crash when completing `LiteralType{Type: cty.Tuple}`

- decoder/expr_tuple_hover.go
- decoder/expr_tuple_hover_test.go
As discovered in #251 
I am not sure if this is the right/best UX, but it is the behaviour we had before, as per the test in #251
> decoder: Display `Tuple` hover data on invalid element

- decoder/expr_list_ref_targets_test.go
- decoder/expr_map_ref_targets_test.go
- decoder/expr_object_ref_targets_test.go
- decoder/expr_set_ref_targets_test.go
- decoder/expr_tuple_ref_targets_test.go
- decoder/reference_targets.go
As discovered in https://github.com/hashicorp/hcl-lang/pull/251
There currently aren't any constraints in the Terraform schema involving _targetable_ `List`/`Set`/`Tuple`/`Map`/`Object` - most occurrences are either not targetable or are implied through `LiteralType` or `AnyExpression`, or part of `OneOf` where `AnyExpression` takes precedence when collecting targets.
TL;DR there's no expected UX impact on Terraform LS users.
This was only discovered because some existing tests being updated in #251
There are situations where the schema may be vague and the user may benefit from seeing the fully inferred type, rather than just `any` in certain contexts. We already do that for the most obvious case of `LiteralType{Type: cty.DynamicPseudoType}` and `AnyExpression{}` equivalent. …
> decoder: Fix collection of implied declared targets of complex types

- decoder/expr_any_ref_targets.go
- decoder/expr_any_ref_targets_test.go
As discovered in #251
In a hypothetical perfect/ideal scenario we could collect just targets which match the type but in reality we cannot always establish the expression type, because:
- we don't recognise all expression types (yet)
- we'd have to re-implement DAG in some way to ensure we collect and interpolate in the right order
- not all variables may be known at editing time (some may be provided only at runtime)
Also it's questionable whether it's beneficial to suppress mismatching targets.
We _mostly_ only do it as a hack to aid `LiteralType` and `Reference` in `OneOf`.
The LOC in the diff may seem high, but 95% of that is a result of copying over all tests for reference target collection from `LiteralType` & replacing `LiteralType{Type}` with `AnyExpression{OfType}` + updating …
> decoder: Collect targets w/ interpolation for `Any` correctly

- decoder/attribute_candidates_legacy_test.go
- decoder/body_candidates_test.go
- decoder/body_extensions_test.go
- decoder/candidates_test.go
- decoder/dependent_body_test.go
- decoder/expr_reference_ref_origins.go
- decoder/expression_candidates_legacy_test.go
- decoder/hover_expressions_legacy_test.go
- decoder/hover_test.go
- decoder/label_candidates_test.go
- decoder/links_test.go
- decoder/reference_origins_collect_hcl_test.go
- decoder/reference_origins_collect_json_test.go
- decoder/reference_targets_collect_extensions_hcl_test.go
- decoder/reference_targets_collect_extensions_json_test.go
- decoder/reference_targets_collect_hcl_test.go
- decoder/reference_targets_collect_json_test.go
- decoder/semantic_tokens_expr_legacy_test.go
- decoder/semantic_tokens_test.go
- decoder/symbols_json_test.go
- schema/attribute_schema_legacy_test.go
- schema/constraint_reference.go
> Update legacy tests to use `Constraint`

- .github/workflows/ci.yml
This is a follow-up to https://github.com/hashicorp/hcl-lang/pull/249 and https://github.com/hashicorp/hcl-lang/pull/201 to ensure we don't introduce new files with missing copyright headers and keep the repository compliant.
> ci: Add PR test for copyright headers

- decoder/validate.go
- decoder/validate_test.go
> Schema based validation

- decoder/body_candidates.go
- decoder/candidates.go
- decoder/extension_schemas.go
- decoder/hover.go
- decoder/internal/schemahelper/attribute_extensions.go
- decoder/internal/walker/walker.go
- decoder/reference_origins.go
- decoder/semantic_tokens.go
- decoder/validate_test.go
This does not raise diagnostics if schema extensions are enabled and Count or ForEach is enabled.
In the work on functions & expressions we introduced the concept of extensions for handling count and for_each. Both aren't part of the regular attributes for a block, but are introduced by enabling the specific extensions for a block.
This adds count and for_each at runtime like completion, hover, and other parts do. Since these are optional attributes, there is are no diagnostics necessary if they are not present.
> Support schema extensions in early validation

- decoder/candidates.go
- decoder/hover.go
- decoder/internal/schemahelper/block_schema.go
- decoder/internal/schemahelper/context.go
- decoder/internal/validator/attribute_unexpected.go
- decoder/internal/validator/block_unexpected.go
- decoder/internal/walker/walker.go
- decoder/reference_origins.go
- decoder/reference_targets.go
- decoder/semantic_tokens.go
- decoder/symbols.go
- decoder/validate_test.go
Depends on https://github.com/hashicorp/hcl-lang/pull/299
Closes https://github.com/hashicorp/hcl-lang/issues/291
--- 
Comments should be self-explanatory and the implementation works exactly as described/desired in https://github.com/hashicorp/hcl-lang/issues/291 - i.e.
> If merging is successful we can continue as normal
> If not, we have to skip some validations, like required attribute/block detection
> If we encounter a attribute/block that still exists in the schema (must be part of the core schema then), we can return to normal validation for that one
This is all driven by a flag which we provide through the context.
> decoder: Enable validators to deal with unknown schema

- decoder/code_lens.go
- decoder/path_context.go
- decoder/validate.go
- lang/validate.go
Add the ability to use the collected origin and target references in early validation.
Validation funcs will be provided by terraform-ls for now.
> Implement reference validation

- lang/validate.go
We need this to check if the length of the diagnostics has changed.
> Implement `Count()` for `DiagnosticsMap`

- decoder/code_lens.go
- decoder/context.go
- decoder/path_context.go
- decoder/validate.go
- lang/validate.go
We move this to the language server in https://github.com/hashicorp/terraform-ls/pull/1361 to decouple it from schema validation and have more fine-grained control over when it runs.
> Remove execution of validation funcs

- decoder/internal/walker/walker.go
- decoder/validate.go
- decoder/validate_test.go
This PR adds a new method to the decoder for validating a single file
> Introduce `decoder.ValidateFile`

- decoder/body_extensions_test.go
- decoder/internal/schemahelper/dynamic_block.go
When `for_each` was initially introduced as a "schema extension" we thought it has the same constraints as the "top level" `for_each` in that it doesn't allow lists. However, since `dynamic` does _not_ have `count` inside, the `for_each` there _does_ allow iterating over lists.
So the updated schema reflects the reality more accurately.
This impacts all functionality driven by schema, i.e.
- completion
- hover
- go-to-definition
- go-to-references
- semantic highlighting
- validation
```hcl
terraform {
required_providers {
cloudinit = {
source  = "hashicorp/cloudinit"
version = "~> 2.3"
}
}
}
variable "parts" {
type = list(object({
filename     = string
content_type = string
content      = string
}))
default = [
{
filename     = "hello-script.sh"
content_type = "text/x-shellscript" …
```
> schemahelper: Allow list(any) to be passed into `dynamic` block's `for_each`

- decoder/body_extensions_test.go
- decoder/hover_test.go
- decoder/internal/schemahelper/dynamic_block.go
This is _mostly_ no-op for existing users but making the schema more accurate here will help us produce more helpful diagnostics as part of the ongoing validation project.
> schemahelper: Make `dynamic` `content` block required

- go.mod
- go.sum
This reflects upstream changes as described in https://github.com/golang/go/issues/62278 and unblocks dependabot which currently cannot run.
An alternative fix would be to add `toolchain 1.21.0` but given that we don't need different version for compatibility and toolchain I think it's easier to just update the `go` directive for now.
See also https://github.com/dependabot/dependabot-core/issues/7895
> go.mod: Fix `go` directive to include patch version

- decoder/internal/schemahelper/context.go
- decoder/internal/validator/block_max_items.go
- decoder/internal/validator/block_min_items.go
- decoder/internal/walker/walker.go
- decoder/validate_test.go
This PR improves the validation of blocks that have the `MinItems` property set. We now account for dynamic blocks for the specific block type.
While we can't evaluate the exact amount of block the dynamic block will generate, we stop raising false negatives.
**Before**
**After**
> Improve `MinItems` validation for `dynamic` blocks

- decoder/candidates.go
- decoder/expr_any_completion.go
- decoder/expr_any_completion_test.go
- decoder/expr_any_hover.go
- decoder/expr_any_hover_test.go
- decoder/expr_any_ref_origins.go
- decoder/expr_any_ref_origins_test.go
- decoder/expr_any_semtok.go
- decoder/expr_any_semtok_test.go
Related:
- https://github.com/hashicorp/terraform-ls/issues/529
Follow-up issue:
- https://github.com/hashicorp/hcl-lang/issues/321
- https://github.com/hashicorp/hcl-lang/issues/325
---
> decoder: Implement completion for binary & unary operators

- decoder/internal/schemahelper/dependent_body.go
- decoder/internal/schemahelper/dependent_body_test.go
- schema/attribute_schema.go
- schema/default_value.go
Related to:
- https://github.com/hashicorp/hcl-lang/issues/120
- https://github.com/hashicorp/vscode-terraform/issues/1573#issuecomment-1748331505
- https://github.com/hashicorp/terraform-schema/pull/270
--- 
This allows us to address the issue surfaced in https://github.com/hashicorp/vscode-terraform/issues/1573#issuecomment-1748331505 without necessarily implementing all the things related to default value handling.
> schema: Introduce `DefaultValue` for `AttributeSchema`

- decoder/expr_object_ref_targets.go
- decoder/expr_tuple_ref_targets.go
- decoder/reference_targets_collect_hcl_test.go
As reported in https://github.com/hashicorp/vscode-terraform/issues/1576 we previously did not collect empty objects and tuples as targets, which caused us to raise this as diagnostics that wasn't relevant.
This PR fixes it and adds some additional tests for some other types just to ensure that we don't introduce similar problem in the future there either.
> (fix) decoder: Ensure empty objects & tuples still get collected as targets

- decoder/body_extensions_test.go
- decoder/hover_test.go
- decoder/internal/schemahelper/attribute_extensions.go
Related to:
- https://github.com/hashicorp/vscode-terraform/issues/1586
--- 
Relevant LOC in Terraform: https://github.com/hashicorp/terraform/blob/07b814c030daae39dea764571bef9cecf26e49be/internal/terraform/eval_for_each.go#L275-L284
As the in-line comment says:
Objects are still supported for backwards-compatible reasons but in general should be avoided. We add it here because otherwise valid configuration would be flagged as invalid. We cannot suppress it in completion (yet) or otherwise inform the user of this anti-pattern though.
> decoder: allow objects in `for_each`

- decoder/expression_candidates_legacy_test.go
- decoder/hover_test.go
- decoder/reference_targets.go
- decoder/reference_targets_collect_hcl_test.go
- decoder/reference_targets_collect_json_test.go
- schema/block_schema.go
This PR removes the concept of inferring types from default values via `AttributeValue`.
See Radek's comment below for more information.
**Before**
**After**
---
* Related to https://github.com/hashicorp/vscode-terraform/issues/1592
> Skip inferring variable type from default values

- decoder/hover.go
- decoder/internal/schemahelper/block_schema.go
- decoder/internal/schemahelper/dependent_body.go
- decoder/internal/schemahelper/dependent_body_test.go
- decoder/internal/walker/walker.go
- decoder/links.go
- decoder/reference_targets.go
As demonstrated by the attached test, we can have a situation of "nested dependent modules" which was previously handled incorrectly. This is best explained on an example.
```hcl
variable "terraform_rs" {
default = {
backend              = "azurerm"
workspace            = "***"
storage_account_name = "***"
container_name       = "***"
key                  = "***"
access_key           = "***"
}
}
data "terraform_remote_state" "this" {
backend   = var.terraform_rs.backend
workspace = var.terraform_rs.workspace
config = {
storage_account_name = var.terraform_rs.storage_account_name
container_name       = var.terraform_rs.container_name
key                  = var.terraform_rs.key
access_key           = var.terraform_rs.access_key
}
}
```
Above, we have multiple dependent body schemas for the …
> decoder: Ensure partially unknown dependent body is handled

- decoder/expr_any_ref_targets.go
- decoder/expr_any_ref_targets_test.go
- decoder/expr_list_ref_targets.go
- decoder/expr_list_ref_targets_test.go
- decoder/expr_literal_type_ref_targets.go
- decoder/expr_literal_type_ref_targets_test.go
- decoder/expr_map_ref_targets.go
- decoder/expr_map_ref_targets_test.go
- decoder/expr_object_ref_targets.go
- decoder/expr_object_ref_targets_test.go
- decoder/expr_set_ref_targets.go
- decoder/expr_tuple_ref_targets.go
- decoder/expr_tuple_ref_targets_test.go
- decoder/reference_targets.go
- decoder/reference_targets_collect_hcl_test.go
- decoder/reference_targets_collect_json_test.go
While working on https://github.com/hashicorp/terraform-schema/pull/292, we discovered that we failed to collect type-unaware targets for attributes with `AsReference` enabled. 
This also led to the discovery that we were incorrectly creating type-aware targets with a NilType, making them a type-unaware target.
This PR fixes all of that, allowing the correct collection of local targets for https://github.com/hashicorp/terraform-schema/pull/292.
> Fix type-unaware target collection

- decoder/expr_list_completion.go
- decoder/expr_list_completion_test.go
- decoder/expr_set_completion.go
- decoder/expr_set_completion_test.go
- decoder/expr_tuple_completion.go
- decoder/expr_tuple_completion_test.go
This PR improves the partial traversal completion within lists, tuples, and sets by recovering the trailing dot.
Since I recently worked on this for template expressions, I thought I could fix it for lists, tuples, and sets as well.
Closes https://github.com/hashicorp/vscode-terraform/issues/1624
> Improve traversal completion for lists, tuples, and sets

- decoder/expr_any_completion.go
- decoder/expr_any_completion_test.go
- decoder/expr_any_hover.go
- decoder/expr_any_hover_test.go
- decoder/expr_any_ref_origins.go
- decoder/expr_any_ref_origins_test.go
- decoder/expr_any_semtok.go
- decoder/expr_any_semtok_test.go
- decoder/expr_literal_type_hover.go
- decoder/expr_literal_type_semtok.go
- decoder/reference_origins_collect_hcl_test.go
* Part of https://github.com/hashicorp/terraform-ls/issues/496
* Related to https://github.com/hashicorp/terraform-ls/issues/522
---
This PR adds support for template expressions inside single and multiline strings.
I filed https://github.com/hashicorp/hcl-lang/issues/345 to track edge cases for empty template expressions inside maps and objects.
`if` directives within template expressions are [turned into conditional expressions](https://github.com/hashicorp/hcl/blob/c964a71ca32006c9e7a0730b5a0e1dd60b05d308/hclsyntax/parser_template.go#L242-L248) and `for` directives are [turned into for expressions](https://github.com/hashicorp/hcl/blob/c964a71ca32006c9e7a0730b5a0e1dd60b05d308/hclsyntax/parser_template.go#L331-L341). So I would defer support for this until those expressions land
* …
> decoder: Support template expressions

- decoder/expr_type_declaration_semtok.go
- decoder/expr_type_declaration_semtok_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_expr_legacy_test.go
- lang/semantic_token.go
This renames the existing token type TokenTypeCapsule to TokenTypeComplex to aid readability and reflect existing naming conventions.
This token represents `list` in `type = list(string)` and similar, i.e. the name of the complex type. The term "capsule" has slightly different meaning in cty and HCL and we should not use it in this context.
> Rename TokenTypeCapsule to TokenTypeComplex

- decoder/expr_any_completion_test.go
- decoder/expr_any_hover_test.go
- decoder/expr_any_operator.go
- decoder/expr_any_ref_origins_test.go
- decoder/expr_any_semtok_test.go
Closes https://github.com/hashicorp/terraform-ls/issues/529
Operators were already implemented as part of https://github.com/hashicorp/hcl-lang/pull/320
--- 
This enables support for parenthesis on the RHS (right hand side), i.e. after `=`.
For example:
```hcl
attr = (var.foo + var.bar) * 2
```
--- 
- https://github.com/hashicorp/terraform-ls/issues/1586
> decoder: Add support for parenthesis on RHS

- decoder/expr_any_completion.go
- decoder/expr_any_completion_test.go
- decoder/expr_any_hover.go
- decoder/expr_any_index.go
- decoder/expr_any_index_test.go
- decoder/expr_any_ref_origins.go
- decoder/expr_any_semtok.go
This PR adds support for references and functions in index expressions. It enables the usual functions like, completion, hover, etc.
With a reference in the index expression, we only collect that reference instead of the whole expression.
---
* Closes https://github.com/hashicorp/terraform-ls/issues/531
> Support complex index expressions

- decoder/expr_any_completion.go
- decoder/expr_any_completion_test.go
- decoder/expr_any_hover.go
- decoder/expr_any_hover_test.go
- decoder/expr_any_ref_origins.go
- decoder/expr_any_ref_origins_test.go
- decoder/expr_any_semtok.go
- decoder/expr_any_semtok_test.go
- decoder/expr_map_completion.go
- decoder/expr_map_hover.go
- decoder/expr_map_ref_origins.go
- decoder/expr_map_semtok.go
- decoder/expr_object_completion.go
- decoder/expr_object_hover.go
- decoder/expr_object_ref_origins.go
- decoder/expr_object_semtok.go
- decoder/expression.go
- schema/constraint_map.go
- schema/constraint_object.go
Depends on:
- https://github.com/hashicorp/hcl-lang/pull/366
--- 
This enables support for interpolated map keys and object attribute names,. Since this is enabled by parenthesis it is closely related to that linked PR which adds support for that expression type.
In other words this enables parenthesis support on the LHS (left hand side).
Example:
```hcl
map_attr = {
(var.keyname) = "foo"
}
```
This does _not_ enable equivalent support inside of inferred maps/objects, such as in the context of Terraform's `locals`. This is currently tracked under https://github.com/hashicorp/terraform-ls/issues/1586 
It originally started out as "hidden implementation detail" of `decoder` (the decision whether interpolation is allowed was originally just implied by `AnyExpression{}` until I realised that …
> decoder: Add support for parenthesis on LHS (map keys & attribute names)

- decoder/expr_any_completion.go
- decoder/expr_any_completion_test.go
- decoder/expr_any_for.go
- decoder/expr_any_hover.go
- decoder/expr_any_hover_test.go
- decoder/expr_any_ref_origins.go
- decoder/expr_any_ref_origins_test.go
- decoder/expr_any_semtok.go
- decoder/expr_any_semtok_test.go
Closes https://github.com/hashicorp/terraform-ls/issues/527
---
> Support `for`-`in`-`if` expressions

- decoder/expr_any_completion_test.go
- decoder/expr_any_template.go
Closes https://github.com/hashicorp/terraform-ls/issues/1611
> Fix prefix completion in `TemplateWrapExpr`

- decoder/expr_any_completion_test.go
- decoder/expr_function.go
- decoder/expr_keyword_completion.go
- decoder/expr_keyword_completion_test.go
- decoder/expr_literal_type_completion.go
- decoder/expr_literal_type_completion_test.go
- decoder/expr_literal_value_completion.go
- decoder/expr_literal_value_completion_test.go
- decoder/expr_type_declaration_completion.go
- decoder/expr_type_declaration_completion_test.go
Radek discovered this crash in the context of a function expression, but it turns out that it affects all expressions that try to infer a prefix.
This PR fixes a crash that occurred when a user tried to use auto-completion in front of a prefix, right after the `=`.
Closes https://github.com/hashicorp/terraform-ls/issues/1606
> Fix crash prefix completion with leading space

- decoder/expr_any_for.go
- decoder/expr_any_ref_origins_test.go
- decoder/expr_one_of_ref_origins.go
#368 added support for `for`-`in`-`if` expressions. Instead of collecting the reference origins inside `for` expressions with the [allowed input constraints](https://developer.hashicorp.com/terraform/language/expressions/for#input-types), we used the constraints of the attribute. This PR fixes that subtle bug.
Fixes https://github.com/hashicorp/vscode-terraform/issues/1693
> Fix `for` expression collection constraints 

- decoder/candidates.go
- decoder/candidates_test.go
- decoder/hover.go
- decoder/hover_test.go
- decoder/reference_origins.go
- decoder/reference_origins_test.go
- decoder/reference_targets.go
- decoder/reference_targets_test.go
- decoder/semantic_tokens.go
- decoder/semantic_tokens_test.go
When Terraform provider defined functions are incomplete (e.g. when completing `provider::`), `hcl` returns a `nil` `Expr` which causes all kinds of panics.
This PR handles such `nil` values for different things.
> fix: `nil` `expr` panics

- decoder/expr_any_completion_test.go
- decoder/expr_any_hover_test.go
- decoder/expr_function.go
- decoder/expression.go
- decoder/expression_test.go
- go.mod
- go.sum
- schema/signature.go
🚫 blocked until there's a new release of `hcl/release` with support for `ExprSyntaxError`:
https://github.com/hashicorp/hcl-lang/blob/905e5636294807904a67f6c89a0562db0b82f32c/go.mod#L8
Closes https://github.com/hashicorp/vscode-terraform/issues/1697
> feat: support namespaced functions

- decoder/candidates_test.go
- decoder/hover_test.go
- decoder/reference_origins_test.go
- decoder/reference_targets_test.go
- decoder/semantic_tokens_test.go
This PR adds only the tests but not the fixes from #376 to show that https://github.com/hashicorp/hcl/pull/668 solves the panics as well.
(the bumped hcl version is the current head of https://github.com/hashicorp/hcl/pull/668)
> test: add test case for panics for invalid namespaced function expressions

- decoder/internal/schemahelper/block_schema.go
- decoder/internal/schemahelper/dynamic_block.go
Different jobs in terraform-ls use the same `hcl.Block` instance simultaneously and the schema merger modified it in the past.
We fixed this by creating a copy first which uncovered another bug: The `buildDynamicBlockSchema` function implicitly read that change from the dependent schema, which we fixed by reading from the `mergedSchema` instead. This in turn required us to also pass the dependent schema into the function as the `mergedSchema` also contains the static `lifecycle` block which can't be set via a dynamic block. This means we now iterate over all blocks in the dependent schema but copy their bodies from the `mergedSchema`.
Fixes #395
>  fix: fix data race in schema merging logic by creating a copy instead of modifying the original struct instance

- decoder/internal/schemahelper/block_schema.go
- decoder/internal/schemahelper/dependent_body_test.go
We couldn't find any cases where the existing tests (and some example codebase) would access the else statement while testing. However, this change could allow e.g. Terraform providers to override for example the lifecycle block if they define such a block in their schema. We have yet to see such cases though :)
> feat: allow overriding existing blocks and attributes for dependent body schemas

- decoder/expr_object_ref_origins.go
This commit adds the collection of origins for object attributes. If an object attribute has an OriginForTarget, it will be collected and returned as part of the object reference origins.
> (TF-18672) Implement collection of object attributes origins

- decoder/expr_literal_value_completion_test.go
- decoder/expr_reference_completion.go
- go.mod
- go.sum
This depends on https://github.com/hashicorp/hcl/pull/692
- **fix: Support reference completions after dot in object constructors**
- **Bump hcl to `117baa8`**
> (TF-19544) fix: Support reference completions with a trailing dot in object constructors

- decoder/expr_object_ref_origins.go
CI currently exits early on `main`, because the `go fmt` step fails
> Fix whitespace via `go fmt`

- .github/workflows/ci.yml
Follow-up to #415. We have never run checks in the CI for any branches that target the `pre-release` branch. I think this is mainly because we rarely make any pre-release changes in hcl-lang.
I think it's still helpful to add this change.
> Run CI on PRs that don't target `main`

- decoder/expr_any_conditional.go
- decoder/expr_any_for.go
- decoder/expr_any_operator.go
- decoder/expr_any_ref_origins.go
- decoder/expr_any_template.go
- decoder/expr_function.go
- decoder/expr_list_ref_origins.go
- decoder/expr_map_ref_origins.go
- decoder/expr_object_ref_origins.go
- decoder/expr_one_of_ref_origins.go
- decoder/expr_reference_ref_origins.go
- decoder/expr_reference_ref_origins_test.go
- decoder/expr_set_ref_origins.go
- decoder/expr_tuple_ref_origins.go
- decoder/expression.go
- decoder/reference_origins.go
This PR refactors a mess in the codebase with `allowSelfRefs` passing around until it reaches the place it was used for.
The helper `schema.WithActiveSelfRefs(ctx)` is already defined by the author, so I just use it for this suppose; and remove the `allowSelfRefs` variable from the method.
Before:
```go
type ReferenceOriginsExpression interface {
ReferenceOrigins(ctx context.Context, allowSelfRefs bool) reference.Origins
}
```
After:
```go
type ReferenceOriginsExpression interface {
ReferenceOrigins(ctx context.Context) reference.Origins
}
```
> decoder: refactor `SelfRefs` use context

- reference/target.go
- reference/targets_test.go
This PR adds a special case when matching references for empty tuple constraints. By default, an empty tuple does not match a tuple with elements. So go-cty's `convert.Convert` doesn't work for tuples.
We now short-circuit the convertible check and always mark empty tuples as matching.
> Fix empty tuple reference matching

- decoder/expr_object_ref_targets.go
- decoder/expr_object_ref_targets_test.go
- decoder/expr_tuple_ref_targets.go
- decoder/expr_tuple_ref_targets_test.go
This PR allows the collection of targets for tuple and object expressions that are created from a for-expression. Previously, we would simply not collect any targets, since a for-expression cannot be converted to a static list or map.
The new target is the same as we would collect for other dynamic types:
https://github.com/hashicorp/hcl-lang/blob/e51d98381d623a627909629610433119b0369f55/decoder/expr_any_ref_targets.go#L29-L48
_Fun side note_: If you use any function calls or variables in the for-expression, we'll hit the code path above instead, because the type refinements will fail due to the empty evaluation context:
https://github.com/hashicorp/hcl-lang/blob/e51d98381d623a627909629610433119b0369f55/decoder/expr_any_ref_targets.go#L19
While this doesn't improve completion due to the …
> Fix target collection from for-expressions

- decoder/attribute_candidates.go
- schema/attribute_schema.go
This change adds support for write only attributes in schema. This is useful for attributes that are write only and should not be read back from the state file.
> (TFECO-7724) Support write only attributes in schema

- decoder/write_only_attributes.go
This adds support for the `PathDecoder` to collect write only attributes used in resources
> feat: Collect write only attributes via PathDecoder
